### ISSUE TITLE
Error when draining all of a Solvent

### ISSUE THREAD

**Issue by beelerchris** [chemgymrl/chemgymrl#134]
An error occurs when the last of a specific solvent is drained.

**Comment by beelerchris** [comment]
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cbeeler/chemgymrl/chemistrylab/extract_bench/extract_bench_v1_engine.py", line 422, in step
    action=action
  File "/home/cbeeler/chemgymrl/chemistrylab/extract_algorithms/extractions/wurtz_v0.py", line 277, in perform_action
    reward = extract_vessel.push_event_to_queue(events=[event], dt=self.dt)
  File "/home/cbeeler/chemgymrl/chemistrylab/chem_algorithms/vessel.py", line 225, in push_event_to_queue
    reward = self._update_materials(dt, check_switches_flag)
  File "/home/cbeeler/chemgymrl/chemistrylab/chem_algorithms/vessel.py", line 271, in _update_materials
    reward += action(parameter=event[1:], dt=dt)
  File "/home/cbeeler/chemgymrl/chemistrylab/chem_algorithms/vessel.py", line 906, in _drain_by_pixel
    self._layers_position_dict.pop(M)
KeyError: 'dodecane'
`

**Comment by beelerchris** [comment]
This may have been fixed as a consequence of solving another issue.

**Comment by beelerchris** [comment]
Error occurs when two solvents are present and one of them is fully drained.
