### ISSUE TITLE
Extract Bench render gives error

### ISSUE THREAD

**Issue by beelerchris** [chemgymrl/chemgymrl#137]
Calling env.render() returns:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cbeeler/chemgymrl/chemistrylab/extract_bench/extract_bench_v1_engine.py", line 492, in render
    self.human_render()
  File "/home/cbeeler/chemgymrl/chemistrylab/extract_bench/extract_bench_v1_engine.py", line 549, in human_render
    1
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/cbeeler/anaconda3/envs/ChemGym/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/cbeeler/anaconda3/envs/ChemGym/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 3 into shape (3,100,1)
`

**Comment by beelerchris** [comment]
Fixed with #153
