### ISSUE TITLE
Unit test failure

### ISSUE THREAD

**Issue by ksprague1** [chemgymrl/chemgymrl#184]
I'm getting a file not found error when running the unit tests.

chloro_wurtz.py does exist so I was wondering if someone could verify this test fails on their setup
(test was conducted on the main branch)

======================================================================
ERROR: test_get_reaction_params (reaction_bench.reaction_base_test.ReactionBaseTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\chemgymrl\tests\unit\reaction_bench\reaction_base_test.py", line 92, in test_get_reaction_params
    reaction_params = env.reaction._get_reaction_params(reaction_filepath=file_path)
  File "C:\Users\sprag\Documents\Python Scripts\ResearchF2022\CHEMGYM\chemgymrl\chemistrylab\reactions\reaction_base.py", line 251, in _get_reaction_params
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1032, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '../../chemistrylab/reactions/available_reactions/chloro_wurtz.py'

----------------------------------------------------------------------
Ran 71 tests in 12.347s

FAILED (errors=2)

**Comment by beelerchris** [comment]
I have not encountered this error in any of my tests. Do you still get this error on main?

**Comment by ksprague1** [comment]
Looks like this was solved by modifying line 72 of reaction_base_test.py at some point.
